/*
Name: Larry Chiem
Class: CST 338-40
Date: Dec. 15, 2020
Assignment Name: (M7) Write a Java program (Simple Android App) (4 hrs)
Language: Java 
Editor: Android Studio
Env: Windows 10 x64 (Ver. 20H2)

*/

package com.example.myapplication;
import android.os.Bundle;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;

/* Main Class that was generated by Android for users to use.
 * @Author Larry Chiem
 */ 

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);



    }



}